export const Constants = {
    WORLD_MAP_SVG_CONTAINER_ID: "WORLD_MAP_SVG_CONTAINER_ID",
    INVENTORY_STACKED_AREA_CHART_SVG_CONTAINER_ID: "INVENTORY_STACKED_AREA_CHART_SVG_CONTAINER_ID",
    BARCHART_COUNTRIES_SVG_CONTAINER_ID: "BARCHART_COUNTRIES_SVG_CONTAINER_ID",
    EXPLOSIONS_STACKED_AREA_CHART_SVG_CONTAINER_ID: "EXPLOSIONS_STACKED_AREA_CHART_SVG_CONTAINER_ID",
    STACKED_BARCHART_TYPE_SVG_CONTAINER_ID: "STACKED_BARCHART_TYPE_SVG_CONTAINER_ID",
    STACKED_HORIZONTAL_BARCHART_TYPE_SVG_CONTAINER_ID: "STACKED_HORIZONTAL_BARCHART_TYPE_SVG_CONTAINER_ID",
}