export const Constants = {
    WORLD_MAP_SVG_CONTAINER_ID: "WORLD_MAP_SVG_CONTAINER_ID",
    BARCHART_COUNTRIES_SVG_CONTAINER_ID: "BARCHART_COUNTRIES_SVG_CONTAINER_ID",
    EXPLOSIONS_STACKED_AREA_CHART_SVG_CONTAINER_ID: "EXPLOSIONS_STACKED_AREA_CHART_SVG_CONTAINER_ID",
    STACKED_BARCHART_TYPE_SVG_CONTAINER_ID: "STACKED_BARCHART_TYPE_SVG_CONTAINER_ID",
    STACKED_HORIZONTAL_BARCHART_TYPE_SVG_CONTAINER_ID: "STACKED_HORIZONTAL_BARCHART_TYPE_SVG_CONTAINER_ID",
    INVENTORY_MULTILINE_CHART_SVG_CONTAINER_ID: "INVENTORY_MULTILINE_CHART_SVG_CONTAINER_ID",
    PCP_SVG_CONTAINER_ID: "PCP_SVG_CONTAINER_ID",
    DISABLED_COLOR: "#EBEBEF",
    NUMERICAL_FEATUREL: "NUMERICAL_FEATURE",
    CATEGORICAL_FEATURE: "CATEGORICAL_FEATURE",
}